#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers


#=================================================
# INSTALLATION
#=================================================

hostname=$(hostname)
rpc_key=$(ynh_app_setting_get --app=reticulum --key=rpc_key)
port_shared_instance=$(ynh_app_setting_get --app=reticulum --key=port_shared_instance)
port_instance_control=$(ynh_app_setting_get --app=reticulum --key=port_instance_control)

pushd $install_dir
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_exec_as_app "$install_dir/venv/bin/pip" install lxmf

    mkdir -p "$install_dir/.lxmf"
    chown "$app:$app" "$install_dir/.lxmf"
    ynh_config_add --jinja --template=config.j2 --destination="$install_dir/.lxmf/config"

    mkdir -p "$install_dir/.reticulum"
    chown "$app:$app" "$install_dir/.reticulum"
    ynh_config_add --jinja --template=reticulum_config.j2 --destination="$install_dir/.reticulum/config"
popd

ynh_config_add_systemd
yunohost service add "$app" --description="LXMF Daemon" --log="/var/log/$app/$app.log"
ynh_config_add_logrotate

systemctl restart reticulum

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
