#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# UPGRADE
#=================================================

pushd $install_dir
	ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade lxmf
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_config_add_systemd
yunohost service add "$app" --description="LXMF Daemon" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
